name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: cargo clippy --release --locked -- -D warnings
      - run: cargo build --release --locked
      - name: Build installer
        shell: pwsh
        run: |
          ./installer/ensure-inno.ps1
          & $env:ISCC /Qp /DAppVersion=0.0.0 installer/open-claude.iss
